server:
   port: 8080
db:
   user: root
   password: root
   name: testdb
   addr: localhost:5432
   
spring:
   profiles:
      include: debug
   datasource:
      continueOnError: true
ldap:
   enabled: true
   url: ldap://ldap.forumsys.com:389
   basedn: dc=example,dc=com
   user: cn=read-only-admin,dc=example,dc=com
   password: password
   userdn: uid={0}
   #url: ldap://localhost:4564
   #basedn: pcds.uni-hildesheim.de

zuul:
   routes:
      heart:
         url: forward:api/v2/heartbeat
      stmgmt:
         url: http://147.172.178.30:3000/

jwt:
   secret: k3l2j4ljsy89/()213kjlA?efDAS"ยง31fdskj23&$%$(jkdasjldkj329)))jdskajf

recovery:
   enabled: true
   password: abcdefgh